=== ValtteriL/OpalOPC/OpalOPC/report-resources/report.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT Report (Targets,StartTime,EndTime,Version,Command,RunStatus,xsl:stylesheet)>
<!ATTLIST Report xmlns:xsi CDATA #REQUIRED>
<!ATTLIST Report xmlns:xsd CDATA #REQUIRED>

<!-- BEGIN Stylesheet -->
<!ELEMENT xsl:stylesheet ANY>
<!ATTLIST xsl:stylesheet id ID #REQUIRED>
<!ATTLIST xsl:stylesheet version CDATA #REQUIRED>
<!ATTLIST xsl:stylesheet xmlns:xsl CDATA #REQUIRED>

<!ELEMENT xsl:output ANY>
<!ATTLIST xsl:output method CDATA #REQUIRED>
<!ATTLIST xsl:output indent CDATA #REQUIRED>
<!ATTLIST xsl:output encoding CDATA #REQUIRED>
<!ATTLIST xsl:output doctype-public CDATA #REQUIRED>
<!ATTLIST xsl:output doctype-system CDATA #REQUIRED>

<!ELEMENT xsl:template ANY>
<!ATTLIST xsl:template match CDATA #REQUIRED>

<!ELEMENT html ANY>
<!ATTLIST html lang CDATA #REQUIRED>

<!ELEMENT head ANY>

<!ELEMENT meta ANY>
<!ATTLIST meta name CDATA #IMPLIED>
<!ATTLIST meta charset CDATA #IMPLIED>
<!ATTLIST meta content CDATA #IMPLIED>
<!ATTLIST meta initial-scale CDATA #IMPLIED>

<!ELEMENT link ANY>
<!ATTLIST link rel CDATA #IMPLIED>
<!ATTLIST link href CDATA #IMPLIED>
<!ATTLIST link type CDATA #IMPLIED>
<!ATTLIST link sizes CDATA #IMPLIED>
<!ATTLIST link crossorigin CDATA #IMPLIED>

<!ELEMENT body ANY>
<!ATTLIST body dir CDATA #IMPLIED>

<!ELEMENT div ANY>
<!ATTLIST div class CDATA #IMPLIED>
<!ATTLIST div style CDATA #IMPLIED>

<!ELEMENT img ANY>
<!ATTLIST img src CDATA #IMPLIED>
<!ATTLIST img alt CDATA #IMPLIED>

<!ELEMENT xsl:copy-of ANY>
<!ATTLIST xsl:copy-of select CDATA #IMPLIED>

<!ELEMENT xsl:value-of ANY>
<!ATTLIST xsl:value-of select CDATA #IMPLIED>

<!ELEMENT xsl:for-each ANY>
<!ATTLIST xsl:for-each select CDATA #IMPLIED>

<!ELEMENT xsl:element ANY>
<!ATTLIST xsl:element name CDATA #IMPLIED>

<!ELEMENT xsl:attribute ANY>
<!ATTLIST xsl:attribute name CDATA #IMPLIED>

<!ELEMENT xsl:when ANY>
<!ATTLIST xsl:when test CDATA #IMPLIED>

<!ELEMENT xsl:variable ANY>
<!ATTLIST xsl:variable name CDATA #IMPLIED>

<!ELEMENT xsl:choose ANY>

<!ELEMENT xsl:if ANY>
<!ATTLIST xsl:if test CDATA #IMPLIED>

<!ELEMENT hr ANY>
<!ATTLIST hr class CDATA #IMPLIED>

<!ELEMENT section ANY>
<!ATTLIST section class CDATA #IMPLIED>

<!ELEMENT p ANY>
<!ATTLIST p class CDATA #IMPLIED>

<!ELEMENT table ANY>
<!ATTLIST table class CDATA #IMPLIED>

<!ELEMENT th ANY>
<!ATTLIST th class CDATA #IMPLIED>

<!ELEMENT title ANY>


<!ELEMENT h1 ANY>
<!ELEMENT h2 ANY>
<!ELEMENT h3 ANY>

<!ELEMENT ul ANY>
<!ATTLIST ul class CDATA #IMPLIED>

<!ELEMENT li ANY>
<!ELEMENT header ANY>

<!ELEMENT tbody ANY>

<!ELEMENT tr ANY>
<!ATTLIST tr class CDATA #IMPLIED>

<!ELEMENT td ANY>
<!ATTLIST td class CDATA #IMPLIED>
<!ATTLIST td colspan CDATA #IMPLIED>

<!ELEMENT thead ANY>
<!ATTLIST thead class CDATA #IMPLIED>

<!ELEMENT span ANY>
<!ATTLIST span class CDATA #IMPLIED>

<!ELEMENT main ANY>

<!ELEMENT script ANY>
<!ATTLIST script src CDATA #IMPLIED>

<!ELEMENT footer ANY>
<!ELEMENT br ANY>

<!ELEMENT a ANY>
<!ATTLIST a target CDATA #IMPLIED>
<!ATTLIST a href CDATA #IMPLIED>
<!-- END Stylesheet -->

<!ELEMENT Targets (Target*)>
<!ELEMENT Target (Servers,Type,ApplicationName,ApplicationUri,ProductUri)>
<!ELEMENT Servers (Server*)>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT ApplicationName (#PCDATA)>
<!ELEMENT ApplicationUri (#PCDATA)>
<!ELEMENT ProductUri (#PCDATA)>

<!ELEMENT Server (DiscoveryUrl,Errors,Endpoints)>
<!ELEMENT Errors (Error*)>
<!ELEMENT Error (Message)>
<!ELEMENT Message (#PCDATA)>

<!ELEMENT Endpoints (Endpoint*)>
<!ELEMENT Endpoint (EndpointUrl,ServerCertificate,SecurityPolicyUris,MessageSecurityModes,UserTokenPolicyIds,UserTokenTypes,Issues)>

<!ELEMENT EndpointUrl (#PCDATA)>
<!ELEMENT ServerCertificate (#PCDATA)>
<!ELEMENT SecurityPolicyUris (SecurityPolicyUri*)>
<!ELEMENT SecurityPolicyUri (#PCDATA)>

<!ELEMENT MessageSecurityModes (MessageSecurityMode*)>
<!ELEMENT MessageSecurityMode (#PCDATA)>

<!ELEMENT UserTokenPolicyIds (UserTokenPolicy*)>
<!ELEMENT UserTokenPolicy (#PCDATA)>

<!ELEMENT UserTokenTypes (UserTokenType*)>
<!ELEMENT UserTokenType (#PCDATA)>

<!ELEMENT Issues (Issue+)>
<!ELEMENT Issue (PluginId,Name,Severity)>
<!ATTLIST Issue xsi:type CDATA #IMPLIED>

<!ELEMENT PluginId (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Severity (#PCDATA)>

<!ELEMENT DiscoveryUrl (#PCDATA)>

<!ELEMENT StartTime (#PCDATA)>
<!ELEMENT EndTime (#PCDATA)>
<!ELEMENT Version (#PCDATA)>
<!ELEMENT Command (#PCDATA)>
<!ELEMENT RunStatus (#PCDATA)>

=== ValtteriL/OpalOPC/test-resources/opalopc-report-all-known.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="http://localhost:8000/OpalOPC/report-resources/stylesheet.xsl"?>
<!DOCTYPE Report SYSTEM "OpalOPC/report-resources/report.dtd">
<Report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Targets>
    <Target>
      <Servers>
        <Server>
          <DiscoveryUrl>opc.tcp://172.16.1.8:53530/OPCUA/SimulationServer</DiscoveryUrl>
          <Errors />
          <Endpoints>
            <Endpoint>
              <EndpointUrl>opc.tcp://172.16.1.8:53530/OPCUA/SimulationServer</EndpointUrl>
              <ServerCertificate>MIIDwzCCAqugAwIBAgIGAYdHKr19MA0GCSqGSIb3DQEBCwUAMEsxHjAcBgNVBAMMFVNpbXVsYXRpb25TZXJ2ZXJAZWNobzETMBEGA1UECgwKUHJvc3lzIE9QQzEUMBIGCgmSJomT8ixkARkWBGVjaG8wHhcNMjMwNDAzMTE0OTU2WhcNMzMwMzMxMTI0OTU2WjBLMR4wHAYDVQQDDBVTaW11bGF0aW9uU2VydmVyQGVjaG8xEzARBgNVBAoMClByb3N5cyBPUEMxFDASBgoJkiaJk/IsZAEZFgRlY2hvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuH25jVIdpLjoyxTo8tYk9+ednAr0qC5SUlo7gCTO+2kWbLoEUGrZJTeOLhhPVC8jEFk+6uxjymrEvzqrPqoihb6ZKH/xjbqbJOrlhIxIrEcG3VxHman/01szj2IYVIJIc3cCQEsmQB16RQzq9/8fXMX+bIbifzx8xRZytl3Ai3n1bA+KJDTDMALb+fzpJ5LqG7ZDUpsV7cDo4r7vs/yL/G8fESWxr17ykfvmlI1QURmiPByaQaxTf+H1ulOGkUQ2wSqAgqtbIHKB1rzj1oFxw1tF7ufpoeXd1VWxEFCkfgrDzwHS+H37V+jeZ4XAFC+Z/1fNgjVyADruLnuwDZ2TMwIDAQABo4GsMIGpMB8GA1UdIwQYMBaAFIpoUFCWmfOVJewDTGkjWPrJmYgsMB0GA1UdDgQWBBSKaFBQlpnzlSXsA0xpI1j6yZmILDAJBgNVHRMEAjAAMAsGA1UdDwQEAwIC9DAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwMAYDVR0RBCkwJ4YfdXJuOmVjaG86T1BDVUE6U2ltdWxhdGlvblNlcnZlcoIEZWNobzANBgkqhkiG9w0BAQsFAAOCAQEABteXY1M4FsxQ+vGaqX3bUpjS8/GA3NIdWA7mBn5M5M5oCqPWpx/LwiMONnpwW2TmnH2kA6JY3vtwvBulXTa01ZqdjRAMX2w2lcaw26BjFbzWYpe328UwQMRsSSbsPS/keSOWSwmIFVwQpe9F0+kApRa1/02kgC6/53ltAylBzN2Hz7ks/U5GyZc0eDO4jc/jnCJAoaJDbnlFVNcyNMaky5ybtTWBDhyGfyA2nF3pK58BGLBQEqjtFG/j7O8FQ77YJTbGKbZ2WEWbbiWBpdzozcBoAJsinb3jy8ppA37/qdKNh7eMOWJrn4GuefINLECXq8o+MFAv8YBRt9Jld9XdQQ==</ServerCertificate>
              <SecurityPolicyUris>
                <SecurityPolicyUri>http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256</SecurityPolicyUri>
                <SecurityPolicyUri>http://opcfoundation.org/UA/SecurityPolicy#Aes128_Sha256_RsaOaep</SecurityPolicyUri>
                <SecurityPolicyUri>http://opcfoundation.org/UA/SecurityPolicy#Basic256</SecurityPolicyUri>
                <SecurityPolicyUri>http://opcfoundation.org/UA/SecurityPolicy#Aes256_Sha256_RsaPss</SecurityPolicyUri>
                <SecurityPolicyUri>http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15</SecurityPolicyUri>
                <SecurityPolicyUri>http://opcfoundation.org/UA/SecurityPolicy#None</SecurityPolicyUri>
              </SecurityPolicyUris>
              <MessageSecurityModes>
                <MessageSecurityMode>SignAndEncrypt</MessageSecurityMode>
                <MessageSecurityMode>Sign</MessageSecurityMode>
                <MessageSecurityMode>None</MessageSecurityMode>
              </MessageSecurityModes>
              <UserTokenPolicyIds>
                <UserTokenPolicy>anonymous</UserTokenPolicy>
                <UserTokenPolicy>certificate_basic128</UserTokenPolicy>
                <UserTokenPolicy>username_basic128</UserTokenPolicy>
                <UserTokenPolicy>certificate_basic256</UserTokenPolicy>
                <UserTokenPolicy>username_basic256</UserTokenPolicy>
              </UserTokenPolicyIds>
              <UserTokenTypes>
                <UserTokenType>Anonymous</UserTokenType>
                <UserTokenType>Certificate</UserTokenType>
                <UserTokenType>UserName</UserTokenType>
              </UserTokenTypes>
              <Issues>
                <Issue>
                  <PluginId>10001</PluginId>
                  <Name>Anonymous authentication enabled</Name>
                  <Severity>7.3</Severity>
                </Issue>
                <Issue>
                  <PluginId>10006</PluginId>
                  <Name>Message Security Mode None</Name>
                  <Severity>6.5</Severity>
                </Issue>
                <Issue>
                  <PluginId>10009</PluginId>
                  <Name>Security Policy None</Name>
                  <Severity>5.4</Severity>
                </Issue>
                <Issue>
                  <PluginId>10002</PluginId>
                  <Name>Auditing disabled</Name>
                  <Severity>5</Severity>
                </Issue>
                <Issue>
                  <PluginId>10008</PluginId>
                  <Name>Deprecated Security Policy Basic256</Name>
                  <Severity>4.8</Severity>
                </Issue>
                <Issue>
                  <PluginId>10007</PluginId>
                  <Name>Deprecated Security Policy Basic128Rsa15</Name>
                  <Severity>4.8</Severity>
                </Issue>
                <Issue>
                  <PluginId>10004</PluginId>
                  <Name>RBAC not supported</Name>
                  <Severity>0</Severity>
                </Issue>
              </Issues>
            </Endpoint>
          </Endpoints>
        </Server>
        <Server>
          <DiscoveryUrl>opc.https://172.16.1.8:53443/OPCUA/SimulationServer</DiscoveryUrl>
          <Errors>
            <Error>
              <Message>Https is not supported: opc.https://172.16.1.8:53443/OPCUA/SimulationServer</Message>
            </Error>
          </Errors>
          <Endpoints />
        </Server>
      </Servers>
      <Type>Server</Type>
      <ApplicationName>SimulationServer@echo</ApplicationName>
      <ApplicationUri>urn:echo:OPCUA:SimulationServer</ApplicationUri>
      <ProductUri>urn:prosysopc.com:OPCUA:SimulationServer</ProductUri>
    </Target>
    <Target>
      <Servers>
        <Server>
          <DiscoveryUrl>opc.tcp://172.16.1.12:53530/OPCUA/SimulationServer</DiscoveryUrl>
          <Errors />
          <Endpoints>
            <Endpoint>
              <EndpointUrl>opc.tcp://172.16.1.12:53530/OPCUA/SimulationServer</EndpointUrl>
              <ServerCertificate>MIIDwzCCAqugAwIBAgIGAYpkI2djMA0GCSqGSIb3DQEBCwUAMEsxHjAcBgNVBAMMFVNpbXVsYXRpb25TZXJ2ZXJAZ29sZjETMBEGA1UECgwKUHJvc3lzIE9QQzEUMBIGCgmSJomT8ixkARkWBGdvbGYwHhcNMjMwOTA1MDU1OTE2WhcNMzMwOTAyMDY1OTE2WjBLMR4wHAYDVQQDDBVTaW11bGF0aW9uU2VydmVyQGdvbGYxEzARBgNVBAoMClByb3N5cyBPUEMxFDASBgoJkiaJk/IsZAEZFgRnb2xmMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0FXmhzztw+yU4xddE8YwbBhwJkrvNLIIRYezMwZD6qlQHdQOwzn2zb8740FFlEy6JykuMbWnMZWNDCbZGbrSJP8xUzXQHokZIFcQShrOg+/0zyqOwX/yVxm0Y+bFp6TTj9xDCoET61PISbI0vsBhSsewWGdF5KkT0R6X2vdto8kTkRlfYNjKL2XunAMuwS5ntExOvWw+1rtZcIhk+S0AA7EtLDLYivwljku4fPDzksPwxAfx7gBtY9qjbtdikmc3u8ek8155kwg8FExOTp1qaODNIInV5hqP/BnZjsrCYeGEL1Y9MMWt9VkhaLGTagmygkcn2lHJx++RNS4HtdTQQwIDAQABo4GsMIGpMB8GA1UdIwQYMBaAFGHfQH4TPfcjnbVU1TCNNlEmv7sdMB0GA1UdDgQWBBRh30B+Ez33I521VNUwjTZRJr+7HTAJBgNVHRMEAjAAMAsGA1UdDwQEAwIC9DAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwMAYDVR0RBCkwJ4YfdXJuOmdvbGY6T1BDVUE6U2ltdWxhdGlvblNlcnZlcoIEZ29sZjANBgkqhkiG9w0BAQsFAAOCAQEAi1/ziHXBjhxf1+X6DD5dkvm91JewZVGTSATIK/xaKCs8gsuvduXWVJQXIiM9S2OaOg6nBxEj08+nhbZ6qLaYTSGJzM4Prmwvog/p91fFmJifRFb+Sh7tByIqqq3ADye1LcFBoDWahXBuoU98kXWlTDj4wJPE2Lsg8z++VZ0hhi0ONj4QprYrI04aYJ+7L6/0PO3D+nMuwVJi4hVzfyEKV2PlIdO4L9OWnRARaGTrGnlD+ngtFwfluYv0RuxzBKgCaE61piDZn21Jxe5ru3kQFy+lITGGF5cNgIw76F0Ci0vMdep1xCUBKxpUfozc+FB8UyVUGvcjBb+lHhDL76KHxQ==</ServerCertificate>
              <SecurityPolicyUris>
                <SecurityPolicyUri>http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15</SecurityPolicyUri>
                <SecurityPolicyUri>http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256</SecurityPolicyUri>
                <SecurityPolicyUri>http://opcfoundation.org/UA/SecurityPolicy#Aes128_Sha256_RsaOaep</SecurityPolicyUri>
                <SecurityPolicyUri>http://opcfoundation.org/UA/SecurityPolicy#Aes256_Sha256_RsaPss</SecurityPolicyUri>
              </SecurityPolicyUris>
              <MessageSecurityModes>
                <MessageSecurityMode>SignAndEncrypt</MessageSecurityMode>
              </MessageSecurityModes>
              <UserTokenPolicyIds>
                <UserTokenPolicy>certificate_basic256</UserTokenPolicy>
                <UserTokenPolicy>username_basic256</UserTokenPolicy>
                <UserTokenPolicy>certificate_basic128</UserTokenPolicy>
                <UserTokenPolicy>anonymous</UserTokenPolicy>
                <UserTokenPolicy>username_basic128</UserTokenPolicy>
              </UserTokenPolicyIds>
              <UserTokenTypes>
                <UserTokenType>Certificate</UserTokenType>
                <UserTokenType>UserName</UserTokenType>
                <UserTokenType>Anonymous</UserTokenType>
              </UserTokenTypes>
              <Issues>
                <Issue>
                  <PluginId>10001</PluginId>
                  <Name>Anonymous authentication enabled</Name>
                  <Severity>7.3</Severity>
                </Issue>
                <Issue>
                  <PluginId>10007</PluginId>
                  <Name>Deprecated Security Policy Basic128Rsa15</Name>
                  <Severity>4.8</Severity>
                </Issue>
              </Issues>
            </Endpoint>
          </Endpoints>
        </Server>
      </Servers>
      <Type>Server</Type>
      <ApplicationName>SimulationServer@golf</ApplicationName>
      <ApplicationUri>urn:golf:OPCUA:SimulationServer</ApplicationUri>
      <ProductUri>urn:prosysopc.com:OPCUA:SimulationServer</ProductUri>
    </Target>
    <Target>
      <Servers>
        <Server>
          <DiscoveryUrl>opc.tcp://172.16.1.13:53530/OPCUA/SimulationServer</DiscoveryUrl>
          <Errors />
          <Endpoints>
            <Endpoint>
              <EndpointUrl>opc.tcp://172.16.1.13:53530/OPCUA/SimulationServer</EndpointUrl>
